spring:
    datasource:
        member:
            jdbc-url: jdbc:mysql://localhost:3306/diary?allowMultiQueries=true&serverTimezone=Asia/Seoul
            username: root
            password: 1234
            driverClassName: com.mysql.cj.jdbc.Driver
            hikari:
                auto-commit: false