spring:
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:mysql://localhost:3306
        username: root
        password: 1234
        hikari:
            auto-commit: false

